### ISSUE TITLE
There seems to be typo on readme 

### ISSUE THREAD

**Issue by thepenguinthatwants** [notusknot/dotfiles-nix#5]
sudo nixos-rebuild switch --flakes .#laptop
It seems to be --flake , instead

**Comment by thepenguinthatwants** [comment]
I guess there is no easy ways to install on and play with this settings.
I am trying to test this on my kvm machine, so ran

`sudo nixos-rebuild switch --flake .#laptop`
File system "/boot" is not a FAT EFI System Partition (ESP) file system.

`                    ./configuration.nix ./config/hosts/laptop.nix ./config/packages.nix `

I took of the  ./config/hosts/laptop.nix for skipping the filesystem stuff

but it still gives

`       - The ‘fileSystems’ option does not specify your root file system.`

So I suppose using flakes one really needs to specify those settings.
In readme there was mention of not using the laptop.nix and/or desktop.nix, but the examples of using flake doesn't mention how to skip using those.

**Comment by notusknot** [comment]
Thank you for commenting, I'll fix the typo

To test with kvm I believe (I am not sure) that you could simply run `sudo nixos-generate-config` to generate a hardware configuration. Then you could either copy it over to replace laptop/desktop.nix, or create a new output in `flake.nix`. 

As an example, these would be the commands you could run:
```sudo nixos-generate-config``` to create a hardware config for your hardware
```cp /etc/nixos/hardware-configuration.nix ~/.config/nixos/config/hosts/laptop.nix``` to replace the laptop.nix hardware file with yours
```sudo nixos-rebuild switch --flake .#laptop``` to build the laptop config with your new hardware config

Hopefully this works!

**Comment by thepenguinthatwants** [comment]
Thanks for the tip

```
[penguin@nixos:~/.config/nixos]$ sudo nixos-rebuild switch --flake .#laptop
building the system configuration...
warning: updating lock file '/home/penguin/.config/nixos/flake.lock':
• Updated input 'neovim-nightly-overlay/neovim-flake/nixpkgs':
    follows 'neovim-nightly-overlay/nixpkgs'
  → 'github:nixos/nixpkgs/b0e141e3fe13ec21f50429773d2e3890e02a80da' (2022-03-12)
File system "/boot" is not a FAT EFI System Partition (ESP) file system.
systemd-boot not installed in ESP.
No default/fallback boot loader installed in ESP.
could not find any previously installed systemd-boot, installing.
File system "/boot" is not a FAT EFI System Partition (ESP) file system.
Traceback (most recent call last):
  File "/nix/store/ayyq0285hvhmznvbc26sbw4w7ngs3lgx-systemd-boot", line 305, in <module>
    main()
  File "/nix/store/ayyq0285hvhmznvbc26sbw4w7ngs3lgx-systemd-boot", line 257, in main
    subprocess.check_call(["/nix/store/24ljibki63lxk0m11qnw8fh9smh64g3x-systemd-249.7/bin/bootctl", "--path=/boot", "update"])
  File "/nix/store/afi0ysqw20yiiw2gr2d28dx40bc4ddf8-python3-3.9.10/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/24ljibki63lxk0m11qnw8fh9smh64g3x-systemd-249.7/bin/bootctl', '--path=/boot', 'update']' returned non-zero exit status 1.
warning: error(s) occurred while switching to the new configuration
```


I guess,  probably some program expects machine to use bootctl or FAT EFI... OH actually probably it somehow tries to use settings from the configuration.nix

**Comment by AkashRajvanshi** [comment]
getting the same "File system "/boot" is not a FAT EFI System Partition (ESP) file system.", can you please help how to solve this issue?? should I need to create efi partition?

**Comment by tipu404** [comment]
Hi, did anyone find a solution to this problem, I am having a similar problem while attempting to rebuild my flake in a Proxomx LXC configured with Nixos?
